name: Build, push and deploy on push to master

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Log into dockerhub
              run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            - name: Download docker build cache
              run: docker-compose -f docker-compose.prod.yml pull webapp
            - name: Build with docker compose
              run: docker-compose -f docker-compose.prod.yml build
            - name: Push docker images to docker hub
              run: docker-compose -f docker-compose.prod.yml push
            - name: Configure deployment credentials
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: ${{ secrets.SSH_HOST }}
                  name: devops_rsa
                  config: |
                    Host ${{ secrets.SSH_USERNAME }}
                        IdentityFile ~/.ssh/devops_rsa
            # Deploy
            - name: Deploy to Production
              uses: fifsky/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  user: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  command: |
                      cd devoops
                      git pull
                      ./deploy.sh
            - name: GH Release
              uses: softprops/action-gh-release@v0.1.5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
